# Generated by Django 4.1.2 on 2022-11-08 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itinerario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospedaje_por_dia',
            fields=[
                ('id_hospedaje', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_hospedaje', models.CharField(max_length=20, verbose_name='tipo hospedaje')),
                ('nombre_hospedaje', models.CharField(max_length=30, verbose_name='nombre hospedaje')),
                ('valor_total_hospedaje', models.IntegerField(verbose_name='valor total')),
                ('direccion_hospedaje', models.CharField(max_length=50, verbose_name='direccion hospedaje')),
                ('fecha_hospedaje', models.DateField(verbose_name='fecha')),
                ('id_itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerario.itinerario')),
            ],
        ),
    ]
