# Generated by Django 4.1.2 on 2022-11-08 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itinerario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='actividad_por_dia',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_actividad', models.CharField(max_length=50, verbose_name='detalle actividad')),
                ('hora_inicio_actividad', models.TimeField(verbose_name='hora inicio')),
                ('hora_final_actividad', models.TimeField(verbose_name='hora final')),
                ('valor_total_actividad', models.IntegerField(verbose_name='valor total')),
                ('fecha_actividad', models.DateField(verbose_name='fecha')),
                ('id_itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerario.itinerario')),
            ],
        ),
    ]
