


REGIONES_CHILE = [
    (1,'Arica y Parinacota','XV'),
	(2,'Tarapacá','I'),
	(3,'Antofagasta','II'),
	(4,'Atacama','III'),
	(5,'Coquimbo','IV'),
	(6,'Valparaiso','V'),
	(7,'Metropolitana de Santiago','RM'),
	(8,'Libertador General Bernardo O\'Higgins','VI'),
	(9,'Maule','VII'),
	(10,'Biobío','VIII'),
	(11,'La Araucanía','IX'),
	(12,'Los Ríos','XIV'),
	(13,'Los Lagos','X'),
	(14,'Aisén del General Carlos Ibáñez del Campo','XI'),
	(15,'Magallanes y de la Antártica Chilena','XII')
]

PROVINCIAS_CHILE = [
    (1,'Arica',1),
	(2,'Parinacota',1),
	(3,'Iquique',2),
	(4,'El Tamarugal',2),
	(5,'Antofagasta',3),
	(6,'El Loa',3),
	(7,'Tocopilla',3),
	(8,'Chañaral',4),
	(9,'Copiapó',4),
	(10,'Huasco',4),
	(11,'Choapa',5),
	(12,'Elqui',5),
	(13,'Limarí',5),
	(14,'Isla de Pascua',6),
	(15,'Los Andes',6),
	(16,'Petorca',6),
	(17,'Quillota',6),
	(18,'San Antonio',6),
	(19,'San Felipe de Aconcagua',6),
	(20,'Valparaiso',6),
	(21,'Chacabuco',7),
	(22,'Cordillera',7),
	(23,'Maipo',7),
	(24,'Melipilla',7),
	(25,'Santiago',7),
	(26,'Talagante',7),
	(27,'Cachapoal',8),
	(28,'Cardenal Caro',8),
	(29,'Colchagua',8),
	(30,'Cauquenes',9),
	(31,'Curicó',9),
	(32,'Linares',9),
	(33,'Talca',9),
	(34,'Arauco',10),
	(35,'Bio Bío',10),
	(36,'Concepción',10),
	(37,'Ñuble',10),
	(38,'Cautín',11),
	(39,'Malleco',11),
	(40,'Valdivia',12),
	(41,'Ranco',12),
	(42,'Chiloé',13),
	(43,'Llanquihue',13),
	(44,'Osorno',13),
	(45,'Palena',13),
	(46,'Aisén',14),
	(47,'Capitán Prat',14),
	(48,'Coihaique',14),
	(49,'General Carrera',14),
	(50,'Antártica Chilena',15),
	(51,'Magallanes',15),
	(52,'Tierra del Fuego',15),
	(53,'Última Esperanza',15)
]


COMUNAS_CHILE = [
    'Arica',
	'Camarones',
	'General Lagos',
	'Putre',
	'Alto Hospicio',
	'Iquique',
	'Camiña',
	'Colchane',
	'Huara',
	'Pica',
	'Pozo Almonte',
	'Antofagasta',
	'Mejillones',
	'Sierra Gorda',
	'Taltal',
	'Calama',
	'Ollague',
	'San Pedro de Atacama',
	'María Elena',
	'Tocopilla',
	'Chañaral',
	'Diego de Almagro',
	'Caldera',
	'Copiapó',
	'Tierra Amarilla',
	'Alto del Carmen',
	'Freirina',
	'Huasco',
	'Vallenar',
	'Canela',
	'Illapel',
	'Los Vilos',
	'Salamanca',
	'Andacollo',
	'Coquimbo',
	'La Higuera',
	'La Serena',
	'Paihuaco',
	'Vicuña',
	'Combarbalá',
	'Monte Patria',
	'Ovalle',
	'Punitaqui',
	'Río Hurtado',
	'Isla de Pascua',
	'Calle Larga',
	'Los Andes',
	'Rinconada',
	'San Esteban',
	'La Ligua',
	'Papudo',
	'Petorca',
	'Zapallar',
	'Hijuelas',
	'La Calera',
	'La Cruz',
	'Limache',
	'Nogales',
	'Olmué',
	'Quillota',
	'Algarrobo',
	'Cartagena',
	'El Quisco',
	'El Tabo',
	'San Antonio',
	'Santo Domingo',
	'Catemu',
	'Llaillay',
	'Panquehue',
	'Putaendo',
	'San Felipe',
	'Santa María',
	'Casablanca',
	'Concón',
	'Juan Fernández',
	'Puchuncaví',
	'Quilpué',
	'Quintero',
	'Valparaíso',
	'Villa Alemana',
	'Viña del Mar',
	'Colina',
	'Lampa',
	'Tiltil',
	'Pirque',
	'Puente Alto',
	'San José de Maipo',
	'Buin',
	'Calera de Tango',
	'Paine',
	'San Bernardo',
	'Alhué',
	'Curacaví',
	'María Pinto',
	'Melipilla',
	'San Pedro',
	'Cerrillos',
	'Cerro Navia',
	'Conchalí',
	'El Bosque',
	'Estación Central',
	'Huechuraba',
	'Independencia',
	'La Cisterna',
	'La Granja',
	'La Florida',
	'La Pintana',
	'La Reina',
	'Las Condes',
	'Lo Barnechea',
	'Lo Espejo',
	'Lo Prado',
	'Macul',
	'Maipú',
	'Ñuñoa',
	'Pedro Aguirre Cerda',
	'Peñalolén',
	'Providencia',
	'Pudahuel',
	'Quilicura',
	'Quinta Normal',
	'Recoleta',
	'Renca',
	'San Miguel',
	'San Joaquín',
	'San Ramón',
	'Santiago',
	'Vitacura',
	'El Monte',
	'Isla de Maipo',
	'Padre Hurtado',
	'Peñaflor',
	'Talagante',
	'Codegua',
	'Coínco',
	'Coltauco',
	'Doñihue',
	'Graneros',
	'Las Cabras',
	'Machalí',
	'Malloa',
	'Mostazal',
	'Olivar',
	'Peumo',
	'Pichidegua',
	'Quinta de Tilcoco',
	'Rancagua',
	'Rengo',
	'Requínoa',
	'San Vicente de Tagua Tagua',
	'La Estrella',
	'Litueche',
	'Marchihue',
	'Navidad',
	'Peredones',
	'Pichilemu',
	'Chépica',
	'Chimbarongo',
	'Lolol',
	'Nancagua',
	'Palmilla',
	'Peralillo',
	'Placilla',
	'Pumanque',
	'San Fernando',
	'Santa Cruz',
	'Cauquenes',
	'Chanco',
	'Pelluhue',
	'Curicó',
	'Hualañé',
	'Licantén',
	'Molina',
	'Rauco',
	'Romeral',
	'Sagrada Familia',
	'Teno',
	'Vichuquén',
	'Colbún',
	'Linares',
	'Longaví',
	'Parral',
	'Retiro',
	'San Javier',
	'Villa Alegre',
	'Yerbas Buenas',
	'Constitución',
	'Curepto',
	'Empedrado',
	'Maule',
	'Pelarco',
	'Pencahue',
	'Río Claro',
	'San Clemente',
	'San Rafael',
	'Talca',
	'Arauco',
	'Cañete',
	'Contulmo',
	'Curanilahue',
	'Lebu',
	'Los Álamos',
	'Tirúa',
	'Alto Biobío',
	'Antuco',
	'Cabrero',
	'Laja',
	'Los Ángeles',
	'Mulchén',
	'Nacimiento',
	'Negrete',
	'Quilaco',
	'Quilleco',
	'San Rosendo',
	'Santa Bárbara',
	'Tucapel',
	'Yumbel',
	'Chiguayante',
	'Concepción',
	'Coronel',
	'Florida',
	'Hualpén',
	'Hualqui',
	'Lota',
	'Penco',
	'San Pedro de La Paz',
	'Santa Juana',
	'Talcahuano',
	'Tomé',
	'Bulnes',
	'Chillán',
	'Chillán Viejo',
	'Cobquecura',
	'Coelemu',
	'Coihueco',
	'El Carmen',
	'Ninhue',
	'Ñiquen',
	'Pemuco',
	'Pinto',
	'Portezuelo',
	'Quillón',
	'Quirihue',
	'Ránquil',
	'San Carlos',
	'San Fabián',
	'San Ignacio',
	'San Nicolás',
	'Treguaco',
	'Yungay',
	'Carahue',
	'Cholchol',
	'Cunco',
	'Curarrehue',
	'Freire',
	'Galvarino',
	'Gorbea',
	'Lautaro',
	'Loncoche',
	'Melipeuco',
	'Nueva Imperial',
	'Padre Las Casas',
	'Perquenco',
	'Pitrufquén',
	'Pucón',
	'Saavedra',
	'Temuco',
	'Teodoro Schmidt',
	'Toltén',
	'Vilcún',
	'Villarrica',
	'Angol',
	'Collipulli',
	'Curacautín',
	'Ercilla',
	'Lonquimay',
	'Los Sauces',
	'Lumaco',
	'Purén',
	'Renaico',
	'Traiguén',
	'Victoria',
	'Corral',
	'Lanco',
	'Los Lagos',
	'Máfil',
	'Mariquina',
	'Paillaco',
	'Panguipulli',
	'Valdivia',
	'Futrono',
	'La Unión',
	'Lago Ranco',
	'Río Bueno',
	'Ancud',
	'Castro',
	'Chonchi',
	'Curaco de Vélez',
	'Dalcahue',
	'Puqueldón',
	'Queilén',
	'Quemchi',
	'Quellón',
	'Quinchao',
	'Calbuco',
	'Cochamó',
	'Fresia',
	'Frutillar',
	'Llanquihue',
	'Los Muermos',
	'Maullín',
	'Puerto Montt',
	'Puerto Varas',
	'Osorno',
	'Puero Octay',
	'Purranque',
	'Puyehue',
	'Río Negro',
	'San Juan de la Costa',
	'San Pablo',
	'Chaitén',
	'Futaleufú',
	'Hualaihué',
	'Palena',
	'Aisén',
	'Cisnes',
	'Guaitecas',
	'Cochrane',
	'O higgins',
	'Tortel',
	'Coihaique',
	'Lago Verde',
	'Chile Chico',
	'Río Ibáñez',
	'Antártica',
	'Cabo de Hornos',
	'Laguna Blanca',
	'Punta Arenas',
	'Río Verde',
	'San Gregorio',
	'Porvenir',
	'Primavera',
	'Timaukel',
	'Natales',
	'Torres del Paine'
]