# Generated by Django 4.1.2 on 2022-11-08 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='casillaItinerario',
            fields=[
                ('id_casilla', models.AutoField(primary_key=True, serialize=False)),
                ('propietario_itinerario', models.CharField(max_length=20, verbose_name='propietario')),
            ],
        ),
        migrations.CreateModel(
            name='itinerario',
            fields=[
                ('id_itinerario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_itinerario', models.CharField(max_length=20, verbose_name='nombre itinerario')),
                ('ciudad_origen_itinerario', models.CharField(max_length=20, verbose_name='ciudad origen')),
                ('fecha_inicio_itinerario', models.DateField(verbose_name='fecha inicio')),
                ('cant_dias_itinerario', models.IntegerField(verbose_name='cantidad dias')),
                ('ciudad_destino_itinerario', models.CharField(max_length=20, verbose_name='ciudad destino')),
                ('id_publico_itinerario', models.IntegerField(verbose_name='id publico')),
                ('publica_privada_itinerario', models.BooleanField(verbose_name='permiso')),
                ('casilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerario.casillaitinerario')),
            ],
        ),
        migrations.AddField(
            model_name='casillaitinerario',
            name='id_itinerario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerario.itinerario'),
        ),
        migrations.AddField(
            model_name='casillaitinerario',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
