# Generated by Django 4.1.2 on 2022-11-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion_usuario',
            field=models.CharField(max_length=100, null=True, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_usuario',
            field=models.IntegerField(null=True, verbose_name='telefono'),
        ),
    ]
