CIUDADES=["ANTOFAGASTA",
                  "ARICA",
                  "BALMACEDA",
                  "CALAMA",
                  "CASTRO CHILOE",
                  "CONCEPCION",
                  "COPIAPO",
                  "IQUIQUE",
                  "LA SERENA",
                  "OSORNO",
                  "PUCON",
                  "PUERTO MONTT",
                  "PUERTO NATALES",
                  "PUNTA ARENAS",
                  "RAPA NUI",
                  "SANTIAGO DE CHILE"
]