# Generated by Django 4.1.2 on 2022-12-09 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itinerario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gastronomia_por_dia',
            fields=[
                ('id_gastronomia', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_gastronomia', models.CharField(max_length=50, verbose_name='detalle gastronomia')),
                ('hora_inicio_gastronomia', models.TimeField(verbose_name='hora inicio')),
                ('hora_final_gastronomia', models.TimeField(verbose_name='hora final')),
                ('valor_total_gastronomia', models.IntegerField(verbose_name='valor total')),
                ('fecha_gastronomia', models.DateField(verbose_name='fecha')),
                ('id_itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerario.itinerario')),
            ],
        ),
    ]
