# Generated by Django 4.1.2 on 2022-11-08 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itinerario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transporte_por_dia',
            fields=[
                ('id_transporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_transporte', models.CharField(max_length=20, verbose_name='nombre itinerario')),
                ('hora_salida_transporte', models.TimeField(verbose_name='hora salida')),
                ('hora_llegada_transporte', models.TimeField(verbose_name='hora llegada')),
                ('valor_total_transporte', models.IntegerField(verbose_name='valor total')),
                ('ciudad_inicio_transporte', models.CharField(max_length=20, verbose_name='ciudad origen')),
                ('ciudad_destino_transporte', models.IntegerField(verbose_name='ciudad destino')),
                ('fecha_transporte', models.DateField(verbose_name='fecha')),
                ('id_itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerario.itinerario')),
            ],
        ),
    ]
